### ISSUE TITLE
Rephrase the sentence in "Release process" regarding "compliant to yocto source"

### ISSUE THREAD

**Issue by thenor** [Pelagicore/software-factory#155]
In the document docs/chapters/workflow/release/release-process.rst we have a sentence which reads "The release process of PELUX sources is compliant to yocto source release which can be found on `Yocto Development Manual`_". This sentence is a bit confusing and it is not clear what is meant by it.
The word 'compliant' is confusing because that word is commonly used with licenses, like "compliant with the GPL" or similar.
What is meant is that if you follow the given link, there is a yocto guide on how to release and zip the sources.

**Comment by sashko** [comment]
@thenor ping

**Comment by thenor** [comment]
The phrasing is still there, but it should be a quick fix. The PR was merged before the issue was found, I think.
