### ISSUE TITLE
Move deployed SWF to pelux.io

### ISSUE THREAD

**Issue by rpannek** [Pelagicore/software-factory#38]
The deployed SWF can be found under https://pelagicore.github.io/software-factory/ right now, but it should be part of the pelux.io website, for example http://pelux.io/software-factory/

For that the deployment job needs to be changed so it puts the results of the build on the right server and then the link on the pelux.io website, in the README and the Website description on top of the GitHub repo page should be changed as well.

**Comment by jeremiah** [comment]
Will moving the deployment mean a different means of deployment? Will we still use Jekyll?

**Comment by rpannek** [comment]
We will still use jekyl but the Jenkins job will move the resulting HTML/CSS files to /var/www/sfw on the server which also serves the pelux.io website instead of committing it back to the gh-pages branch in the git repo so that GitHub can serve it.

**Comment by tobsan** [comment]
This would be similar to how we build the main pelux.io website, I suppose?

**Comment by rpannek** [comment]
Oh wait, yes @tobsan you are right, but we would keep using Sphinx, I misread what @jeremiah wrote it's not Jekyl we use but Sphinx.

**Comment by GordanM** [comment]
Can we close this issue?

**Comment by rpannek** [comment]
Yes, closing.
