### ISSUE TITLE
repo init ... <branch> doesn't hint me what I should use

### ISSUE THREAD

**Issue by rpannek** [Pelagicore/software-factory#46]
When someone reads the documentation about "Building PELUX sources" and they get to the `repo init` line, they have no idea on what to chose there. There should be at least a hint to choose master if you're just trying it out or something, better additionally a link to a description about what those mean.

**Comment by tobsan** [comment]
Good point. At least we should say master or "latest yocto release" with a link to the yocto releases

**Comment by GordanM** [comment]
@rpannek I believe this issue can be closed right? When I look at the page (http://pelux.io/software-factory/master/chapters/baseplatform/building-PELUX-sources.html#building-locally) it seems quite clear to me.

**Comment by tobsan** [comment]
@GordanM it will be closed soon anyway :)

**Comment by rpannek** [comment]
@GordanM uhm, so where does it say what you should replace `<branch>` with when you're just a random person who wants to build a PELUX image with this? What would you chose and why?
