### ISSUE TITLE
Remove empty Architecture pages

### ISSUE THREAD

**Issue by rpannek** [Pelagicore/software-factory#81]
For some reason empty architecture pages got in into SWF, those should be removed and only added once there is content.

see: http://pelux.io/software-factory/master/chapters/architecture/index.html pp

It's really bad practice to put empty headlines into a documentation which suggest a lot of content but then don't deliver.

**Comment by GordanM** [comment]
@rpannek I agree, though since we work in a distributed setup something has to be populated to enable others to start working on it, without them actually creating the structure. Not sure what would be the best way around this? Perhaps a feature branch upstream or? Do you have any suggestions?

**Comment by rpannek** [comment]
Yes a feature branch would be the way to go I guess. The problem is that I got questions from people about why the architecture stuff is empty who haven't been involved in the project (yet) and this was confusing. A feature branch should be able to be integrated to the CI quite easyly.

**Comment by GordanM** [comment]
Point taken. Thanks for the feedback @rpannek, I'll tend to it that the pages are removed from the SWF. They will remain in the blueprint and the baseline SWF but never referenced so they should not appear. Does that sound ok?

**Comment by rpannek** [comment]
Yes that would be good enough.
